/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.5.0.0 (NJsonSchema v10.1.15.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import Api from "./Api";
import Loadable from "./Loadable";

export class AuthenticationApi {
    signIn = (command: SignInCommand, loadable?: Loadable<IErrors>) =>
        Api.post("/Authentication/signin", command, loadable);
    
    signOut = (loadable?: Loadable<void>) =>
        Api.post("/Authentication/signout", undefined, loadable);
    
    me = (loadable?: Loadable<UserModel>) =>
        Api.get("/Authentication/me", undefined, loadable);
    
}

export class DinosaursApi {
    post = (command: CreateDinosaurCommand, loadable?: Loadable<IErrors>) =>
        Api.post("/Dinosaurs", command, loadable);
    
}

export interface IErrors {
}

export interface SignInCommand {
    email?: string | undefined;
    password?: string | undefined;
}

export interface UserModel {
    id?: string;
    email?: string | undefined;
}

export interface CreateDinosaurCommand {
    id?: string;
    name?: string | undefined;
}